apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-app
spec:
  replicas: 1  # For demo, keep 1 replica; scale as needed
  selector:
    matchLabels:
      app: ttt
  template:
    metadata:
      labels:
        app: ttt
    spec:
      containers:
        - name: ttt
          image: ttt-app:latest  # Ensure this image tag is correct
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:  # Optional: Add any environment variables here
            - name: NODE_ENV
              value: "production"
          resources:  # Ensure resource limits and requests are set
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          # Adding liveness and readiness probes for better health management

---
apiVersion: v1
kind: Service
metadata:
  name: ttt-svc
spec:
  selector:
    app: ttt
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---
# OPTIONAL: Ingress (requires an Ingress Controller in cluster)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ttt-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Ensure you have NGINX ingress controller installed
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ttt-svc
                port:
                  number: 5000
