name: Node App CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and run tests
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "No tests found"

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t node-demo:latest .

      # Load image into KIND cluster
      - name: Load Image into KIND
        run: |
          kind load docker-image node-demo:latest

      # Apply Kubernetes manifests
      - name: Deploy to KIND
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/node-demo
